# GoReleaser configuration for SLSA Go builder
# This configuration is used by the official SLSA Go builder

version: 1

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: zobra-go
    binary: zobra-go
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: zobra-go-archive
    builds:
      - zobra-go
    name_template: "zobra-go_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "zobra-go_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  draft: false
  prerelease: false
  name_template: "Zobra Go {{ .Version }}"
  header: |
    ## 🎯 Zobra Go {{ .Version }}
    
    This release includes **SLSA Level 3 provenance** generated by the official SLSA Go builder.
    
    ### 🔒 Security Features:
    - ✅ Official SLSA Level 3 provenance
    - ✅ Cryptographic attestation  
    - ✅ Transparency log recording
    - ✅ Trusted by slsa-verifier
    
    ### 📦 Verification:
    ```bash
    # Download the binary and provenance
    gh release download {{ .Tag }} --repo {{ .Env.GITHUB_REPOSITORY }}
    
    # Verify with slsa-verifier (should show PASSED!)
    slsa-verifier verify-artifact zobra-go_{{ .Version }}_linux_amd64.tar.gz \
      --provenance-path zobra-go_{{ .Version }}_linux_amd64.tar.gz.intoto.jsonl \
      --source-uri github.com/{{ .Env.GITHUB_REPOSITORY }} \
      --source-tag {{ .Tag }}
    ```
