name: Official Go SLSA Builder

on:
  push:
    tags:
      - 'go-v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., go-v1.0.0)'
        required: true
        default: 'go-v1.0.0'

permissions: read-all

jobs:
  # This job uses the OFFICIAL SLSA Go builder
  # It will generate trusted SLSA Level 3 provenance
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read   # To read the workflow path.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.10.0
    with:
      go-version: "1.21"
      # Build configuration
      config-file: .slsa-goreleaser.yml
      # Upload to release
      upload-assets: true
      upload-tag-name: ${{ github.event.inputs.tag || github.ref_name }}
